name: Build and Release
on:
    push:
        tags:
            - "*"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: TypeScript
              run: npm run typescript

            - name: Test
              run: npm run test

            - name: Bundle
              run: npm run build

            - name: Package
              run: zip -j obsidian-task-archiver.zip main.js manifest.json styles.css

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  name: ${{  github.ref_name }}
                  tag_name: ${{ github.ref }}
                  files: |
                      obsidian-task-archiver.zip
                      main.js
                      manifest.json
                      styles.css
